<?php
if(!defined('ABSPATH'))exit;
class Studio_Google_Calendar{
 private static $instance;public static function get_instance(){return self::$instance?:(self::$instance=new self());}
 private function __construct(){add_action('admin_menu',array($this,'menu'));add_action('admin_init',array($this,'actions'));add_action('studio_hourly_reminders',array($this,'reminders'));if(!wp_next_scheduled('studio_hourly_reminders'))wp_schedule_event(time()+300,'hourly','studio_hourly_reminders');}
 public function menu(){add_submenu_page('studio-professionale','Agenda e Google Calendar','Agenda',Studio_Roles::CAP_EDIT_PATIENTS,'studio-agenda',array($this,'page'));}
 private function redirect_uri(){return admin_url('admin.php?page=studio-agenda&google_callback=1');}
 private function setting($k,$d=''){return Studio_DB::get_setting($k,$d);} private function set($k,$v){return Studio_DB::update_setting($k,$v);}
 private function request($method,$url,$body=null,$token=''){ $args=array('method'=>$method,'timeout'=>20,'headers'=>array('Accept'=>'application/json'));if($token)$args['headers']['Authorization']='Bearer '.$token;if($body!==null){$args['headers']['Content-Type']='application/json';$args['body']=wp_json_encode($body);}return wp_remote_request($url,$args);}
 private function token(){ $t=$this->setting('google_token',array());if(!empty($t['expires_at'])&&$t['expires_at']>time()+60)return $t['access_token'];if(empty($t['refresh_token']))return ''; $r=wp_remote_post('https://oauth2.googleapis.com/token',array('body'=>array('client_id'=>$this->setting('google_client_id'),'client_secret'=>$this->setting('google_client_secret'),'refresh_token'=>$t['refresh_token'],'grant_type'=>'refresh_token')));$j=json_decode(wp_remote_retrieve_body($r),true);if(empty($j['access_token']))return '';$t['access_token']=$j['access_token'];$t['expires_at']=time()+intval($j['expires_in']??3600);$this->set('google_token',$t);return $t['access_token'];}
 public function actions(){if(isset($_POST['studio_google_save'])){check_admin_referer('studio_google');if(!current_user_can(Studio_Roles::CAP_MANAGE_STUDIO))wp_die('Accesso negato');$this->set('google_client_id',sanitize_text_field($_POST['client_id']));$this->set('google_client_secret',sanitize_text_field($_POST['client_secret']));$this->set('google_calendar_id',sanitize_text_field($_POST['calendar_id']?:'primary'));wp_safe_redirect(admin_url('admin.php?page=studio-agenda&saved=1'));exit;}if(isset($_GET['google_callback'],$_GET['code'])){check_admin_referer('studio_google_connect','state');$r=wp_remote_post('https://oauth2.googleapis.com/token',array('body'=>array('code'=>sanitize_text_field($_GET['code']),'client_id'=>$this->setting('google_client_id'),'client_secret'=>$this->setting('google_client_secret'),'redirect_uri'=>$this->redirect_uri(),'grant_type'=>'authorization_code')));$j=json_decode(wp_remote_retrieve_body($r),true);if(!empty($j['access_token'])){$j['expires_at']=time()+intval($j['expires_in']??3600);$this->set('google_token',$j);}wp_safe_redirect(admin_url('admin.php?page=studio-agenda'));exit;}if(isset($_POST['studio_appointment'])){check_admin_referer('studio_appointment');global $wpdb;$start=sanitize_text_field($_POST['inizio']);$end=date('Y-m-d H:i:s',strtotime($start)+max(15,intval($_POST['durata']))*60);$data=array('paziente_id'=>intval($_POST['paziente_id']),'inizio'=>$start,'fine'=>$end,'titolo'=>sanitize_text_field($_POST['titolo']),'note'=>sanitize_textarea_field($_POST['note']),'data_creazione'=>current_time('mysql'));$wpdb->insert(Studio_DB::table('appuntamenti'),$data);$id=$wpdb->insert_id;$token=$this->token();if($token){$event=array('summary'=>$data['titolo'],'description'=>$data['note'],'start'=>array('dateTime'=>date(DATE_RFC333,strtotime($start))),'end'=>array('dateTime'=>date(DATE_RFC333,strtotime($end))));$cid=rawurlencode($this->setting('google_calendar_id','primary'));$r=$this->request('POST','https://www.googleapis.com/calendar/v3/calendars/'.$cid.'/events',$event,$token);$j=json_decode(wp_remote_retrieve_body($r),true);if(!empty($j['id']))$wpdb->update(Studio_DB::table('appuntamenti'),array('google_event_id'=>$j['id']),array('id'=>$id));}wp_safe_redirect(admin_url('admin.php?page=studio-agenda'));exit;}}
 public function page(){global $wpdb;$patients=$wpdb->get_results('SELECT id,nome,cognome FROM '.Studio_DB::table('pazienti').' ORDER BY cognome,nome');$events=$wpdb->get_results('SELECT a.*,p.nome,p.cognome FROM '.Studio_DB::table('appuntamenti').' a LEFT JOIN '.Studio_DB::table('pazienti').' p ON p.id=a.paziente_id ORDER BY inizio DESC LIMIT 100');$connected=(bool)$this->token();$auth='https://accounts.google.com/o/oauth2/v2/auth?'.http_build_query(array('client_id'=>$this->setting('google_client_id'),'redirect_uri'=>$this->redirect_uri(),'response_type'=>'code','scope'=>'https://www.googleapis.com/auth/calendar.events','access_type'=>'offline','prompt'=>'consent','state'=>wp_create_nonce('studio_google_connect')));include STUDIO_PROF_PATH.'templates/agenda.php';}
 public function reminders(){global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT a.*,p.email,p.nome FROM '.Studio_DB::table('appuntamenti').' a JOIN '.Studio_DB::table('pazienti').' p ON p.id=a.paziente_id WHERE a.promemoria_inviato=0 AND a.inizio BETWEEN %s AND %s',current_time('mysql'),date('Y-m-d H:i:s',current_time('timestamp')+DAY_IN_SECONDS)));foreach($rows as $r)if(is_email($r->email)&&wp_mail($r->email,'Promemoria appuntamento','Gentile '.$r->nome.', appuntamento il '.date_i18n('d/m/Y H:i',strtotime($r->inizio))))$wpdb->update(Studio_DB::table('appuntamenti'),array('promemoria_inviato'=>1),array('id'=>$r->id));}
}
