<?php
if (!defined('ABSPATH')) exit;
class Studio_PWA {
 private static $instance=null;
 public static function get_instance(){return self::$instance?:self::$instance=new self();}
 private function __construct(){add_action('init',array($this,'rewrites'));add_action('init',array($this,'maybe_flush'),99);add_filter('query_vars',function($v){$v[]='studio_pwa';return $v;});add_action('template_redirect',array($this,'route'));add_action('rest_api_init',array($this,'rest'));add_filter('show_admin_bar',array($this,'hide_bar'));add_action('admin_init',array($this,'redirect_professional'));}
 public function rewrites(){add_rewrite_rule('^studio-app/?$','index.php?studio_pwa=app','top');add_rewrite_rule('^studio-app/manifest\.webmanifest$','index.php?studio_pwa=manifest','top');add_rewrite_rule('^studio-app/service-worker\.js$','index.php?studio_pwa=sw','top');add_rewrite_rule('^studio-app/offline/?$','index.php?studio_pwa=offline','top');}
 public static function activate(){self::get_instance()->rewrites();flush_rewrite_rules();update_option('studio_pwa_rewrite_version',STUDIO_PROF_VERSION);}
 public function maybe_flush(){if(get_option('studio_pwa_rewrite_version')!==STUDIO_PROF_VERSION){flush_rewrite_rules(false);update_option('studio_pwa_rewrite_version',STUDIO_PROF_VERSION);}}
 private function is_professional(){return current_user_can(Studio_Roles::CAP_VIEW_CLINICAL)&&!current_user_can('manage_options');}
 public function hide_bar($show){return $this->is_professional()?false:$show;}
 public function redirect_professional(){if($this->is_professional()&&!wp_doing_ajax()&&(!defined('REST_REQUEST')||!REST_REQUEST)){wp_safe_redirect(home_url('/studio-app/'));exit;}}
 public function route(){$r=get_query_var('studio_pwa');if(!$r)return;if($r==='manifest')$this->manifest();if($r==='sw')$this->service_worker();if($r==='offline')$this->offline();$this->app();}
 private function no_store(){nocache_headers();header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: same-origin');}
 private function manifest(){header('Content-Type: application/manifest+json; charset=utf-8');echo wp_json_encode(array('name'=>'Studio Professionale','short_name'=>'Studio','description'=>'Gestione clinica e contabile dello studio','start_url'=>home_url('/studio-app/'),'scope'=>home_url('/studio-app/'),'display'=>'standalone','background_color'=>'#f8fafc','theme_color'=>'#2563eb','icons'=>array(array('src'=>STUDIO_PROF_URL.'pwa/icons/icon-192.png','sizes'=>'192x192','type'=>'image/png'),array('src'=>STUDIO_PROF_URL.'pwa/icons/icon-512.png','sizes'=>'512x512','type'=>'image/png'),array('src'=>STUDIO_PROF_URL.'pwa/icons/icon-maskable-512.png','sizes'=>'512x512','type'=>'image/png','purpose'=>'maskable'))),JSON_UNESCAPED_SLASHES);exit;}
 private function service_worker(){header('Content-Type: application/javascript; charset=utf-8');header('Service-Worker-Allowed: '.wp_parse_url(home_url('/studio-app/'),PHP_URL_PATH));readfile(STUDIO_PROF_PATH.'pwa/service-worker.js');exit;}
 private function offline(){header('Content-Type: text/html; charset=utf-8');readfile(STUDIO_PROF_PATH.'pwa/offline.html');exit;}
 private function app(){if(isset($_POST['studio_pwa_login'])){check_admin_referer('studio_pwa_login');$u=wp_signon(array('user_login'=>sanitize_text_field(wp_unslash($_POST['log']??'')),'user_password'=>(string)($_POST['pwd']??''),'remember'=>!empty($_POST['remember'])),is_ssl());if(is_wp_error($u))$login_error='Credenziali non valide.';else{wp_safe_redirect(home_url('/studio-app/'));exit;}}if(isset($_GET['studio_logout'])){wp_logout();wp_safe_redirect(home_url('/studio-app/'));exit;}$this->no_store();header('Content-Type: text/html; charset=utf-8');$logged=is_user_logged_in();$allowed=$logged&&current_user_can(Studio_Roles::CAP_VIEW_CLINICAL);$rest_nonce=$allowed?wp_create_nonce('wp_rest'):'';include STUDIO_PROF_PATH.'pwa/index.php';exit;}
 public function permission_view(){return is_user_logged_in()&&current_user_can(Studio_Roles::CAP_VIEW_CLINICAL);}
 public function permission_edit(){return is_user_logged_in()&&current_user_can(Studio_Roles::CAP_EDIT_PATIENTS);}
 public function permission_docs(){return is_user_logged_in()&&current_user_can(Studio_Roles::CAP_MANAGE_DOCUMENTS);}
 public function permission_invoices(){return is_user_logged_in()&&current_user_can(Studio_Roles::CAP_MANAGE_INVOICES);}
 private function args($methods,$cb,$perm){return array('methods'=>$methods,'callback'=>array($this,$cb),'permission_callback'=>array($this,$perm));}
 public function rest(){$n='studio/v1';register_rest_route($n,'/app-config',$this->args('GET','api_config','permission_view'));register_rest_route($n,'/dashboard',$this->args('GET','api_dashboard','permission_view'));register_rest_route($n,'/patients',$this->args('GET','api_patients','permission_view'));register_rest_route($n,'/patients/(?P<id>\d+)',$this->args('GET','api_patient','permission_view'));register_rest_route($n,'/patients/(?P<id>\d+)/anamnesis',$this->args('POST','api_anamnesis','permission_edit'));register_rest_route($n,'/patients/(?P<id>\d+)/visits',$this->args(array('GET','POST'),'api_visits','permission_edit'));register_rest_route($n,'/visits/(?P<id>\d+)',$this->args(array('PUT','DELETE'),'api_visit','permission_edit'));register_rest_route($n,'/patients/(?P<id>\d+)/clinical-profile',$this->args(array('GET','POST'),'api_profile','permission_edit'));register_rest_route($n,'/patients/(?P<id>\d+)/documents',$this->args(array('GET','POST'),'api_documents','permission_docs'));register_rest_route($n,'/patients/(?P<id>\d+)/invoices',$this->args('GET','api_patient_invoices','permission_invoices'));register_rest_route($n,'/accounting',$this->args('GET','api_accounting','permission_invoices'));register_rest_route($n,'/invoices',$this->args('GET','api_invoice_list','permission_invoices'));register_rest_route($n,'/invoices/(?P<id>\d+)',$this->args('GET','api_invoice','permission_invoices'));}
 private function response($d){$r=rest_ensure_response($d);$r->header('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');$r->header('X-Content-Type-Options','nosniff');return $r;}
 private function age($d){if(!$d||$d==='0000-00-00')return null;try{$b=new DateTime($d);$t=new DateTime(current_time('Y-m-d'));return $b>$t?null:$b->diff($t)->y;}catch(Exception $e){return null;}}
 private function patient($id){global $wpdb;return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.Studio_DB::table('pazienti').' WHERE id=%d',$id));}
 public function api_config(){$s=Studio_DB::get_studio_data();$u=wp_get_current_user();return $this->response(array('studio'=>array('denominazione'=>$s['denominazione'],'partita_iva'=>$s['partita_iva'],'professionista'=>$s['professionista']),'user'=>array('display_name'=>$u->display_name),'app'=>array('version'=>STUDIO_PROF_VERSION)));}
 public function api_dashboard(){global $wpdb;$p=Studio_DB::table('pazienti');$v=Studio_DB::table('visite');$recent=$wpdb->get_results("SELECT id,nome,cognome,data_nascita FROM $p ORDER BY id DESC LIMIT 6");foreach($recent as $x)$x->age=$this->age($x->data_nascita);return $this->response(array('patients'=>array('total'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $p"),'male'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $p WHERE UPPER(sesso)='M'"),'female'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $p WHERE UPPER(sesso)='F'")),'recent_patients'=>$recent,'recent_visits'=>$wpdb->get_results("SELECT v.id,v.paziente_id,v.data_visita,v.tipo_seduta,p.nome,p.cognome FROM $v v JOIN $p p ON p.id=v.paziente_id ORDER BY v.data_visita DESC LIMIT 6")));}
 public function api_patients($r){global $wpdb;$q=sanitize_text_field($r->get_param('search')??'');$t=Studio_DB::table('pazienti');$w='';if($q!==''){$l='%'.$wpdb->esc_like($q).'%';$w=$wpdb->prepare(' WHERE nome LIKE %s OR cognome LIKE %s OR codice_fiscale LIKE %s OR telefono LIKE %s',$l,$l,$l,$l);}$rows=$wpdb->get_results("SELECT id,nome,cognome,data_nascita FROM $t$w ORDER BY cognome,nome LIMIT 100");foreach($rows as $x)$x->age=$this->age($x->data_nascita);return $this->response($rows);}
 public function api_patient($r){$p=$this->patient((int)$r['id']);if(!$p)return new WP_Error('not_found','Paziente non trovato',array('status'=>404));$p->age=$this->age($p->data_nascita);return $this->response(array('patient'=>$p,'profile'=>Studio_Clinical_Profile::get($p->id),'categories'=>Studio_Clinical_Profile::vocabulary()));}
 public function api_anamnesis($r){$id=(int)$r['id'];if(!$this->patient($id))return new WP_Error('not_found','Paziente non trovato',array('status'=>404));global $wpdb;$text=wp_kses_post((string)$r->get_param('anamnesis'));$old=$wpdb->get_var($wpdb->prepare('SELECT anamnesi FROM '.Studio_DB::table('pazienti').' WHERE id=%d',$id));$wpdb->update(Studio_DB::table('pazienti'),array('anamnesi'=>$text,'data_aggiornamento'=>current_time('mysql')),array('id'=>$id));Studio_Security::audit('modifica_anamnesi_pwa','paziente',$id,array('prima'=>$old,'dopo'=>$text));return $this->response(array('saved'=>true));}
 private function visit_data($r){return array('data_visita'=>sanitize_text_field($r->get_param('date')),'durata_minuti'=>max(1,(int)$r->get_param('duration')),'tipo_seduta'=>sanitize_text_field($r->get_param('type')),'note'=>wp_kses_post((string)$r->get_param('notes')),'completata'=>(int)($r->get_param('completed')!==0));}
 public function api_visits($r){$id=(int)$r['id'];global $wpdb;$t=Studio_DB::table('visite');if($r->get_method()==='GET')return $this->response($wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE paziente_id=%d ORDER BY data_visita DESC",$id)));$d=$this->visit_data($r);$d['paziente_id']=$id;$d['data_creazione']=current_time('mysql');$wpdb->insert($t,$d);Studio_Security::audit('aggiunta_visita_pwa','paziente',$id,array('visita_id'=>$wpdb->insert_id));return $this->response(array('saved'=>true,'id'=>$wpdb->insert_id));}
 public function api_visit($r){global $wpdb;$id=(int)$r['id'];$t=Studio_DB::table('visite');$old=$wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d",$id),ARRAY_A);if(!$old)return new WP_Error('not_found','Seduta non trovata',array('status'=>404));if($r->get_method()==='DELETE'){$wpdb->delete($t,array('id'=>$id));Studio_Security::audit('eliminazione_visita_pwa','visita',$id,array('prima'=>$old));return $this->response(array('deleted'=>true));}$d=$this->visit_data($r);$wpdb->update($t,$d,array('id'=>$id));Studio_Security::audit('modifica_visita_pwa','visita',$id,array('prima'=>$old,'dopo'=>$d));return $this->response(array('saved'=>true));}
 public function api_profile($r){$id=(int)$r['id'];if($r->get_method()==='GET')return $this->response(array('profile'=>Studio_Clinical_Profile::get($id),'categories'=>Studio_Clinical_Profile::vocabulary()));$raw=$r->get_param('profile');if(!is_array($raw))$raw=array();$allowed=array();foreach(Studio_Clinical_Profile::vocabulary() as $c)$allowed[$c['id']]=array_flip($c['items']);$clean=array();foreach($raw as $cid=>$items){$cid=sanitize_key($cid);if(!isset($allowed[$cid])||!is_array($items))continue;foreach($items as $i){$i=sanitize_text_field($i);if(isset($allowed[$cid][$i]))$clean[$cid][]=$i;}}global $wpdb;$old=Studio_Clinical_Profile::get($id);$wpdb->replace(Studio_DB::table('profili_clinici'),array('paziente_id'=>$id,'profilo_json'=>wp_json_encode($clean,JSON_UNESCAPED_UNICODE),'utente_modifica'=>get_current_user_id(),'data_creazione'=>current_time('mysql'),'data_aggiornamento'=>current_time('mysql')));Studio_Security::audit('modifica_profilo_clinico_pwa','paziente',$id,array('prima'=>$old,'dopo'=>$clean));return $this->response(array('saved'=>true));}
 public function api_documents($r){$id=(int)$r['id'];global $wpdb;if($r->get_method()==='POST'){if(empty($_FILES['file']['tmp_name']))return new WP_Error('missing_file','Selezionare un PDF',array('status'=>422));$f=$_FILES['file'];if((int)$f['size']>10*1024*1024)return new WP_Error('too_large','Il PDF supera 10 MB',array('status'=>413));$c=wp_check_filetype_and_ext($f['tmp_name'],$f['name'],array('pdf'=>'application/pdf'));if($c['ext']!=='pdf'||$c['type']!=='application/pdf')return new WP_Error('invalid_file','Sono ammessi solo PDF validi',array('status'=>422));$u=wp_upload_dir();$dir=$u['basedir'].'/studio-professionale-docs/patient-'.$id;wp_mkdir_p($dir);$name=wp_unique_filename($dir,sanitize_file_name($f['name']));$path=$dir.'/'.$name;if(!move_uploaded_file($f['tmp_name'],$path))return new WP_Error('upload_failed','Caricamento non riuscito',array('status'=>500));$wpdb->insert(Studio_DB::table('documenti'),array('paziente_id'=>$id,'nome_file'=>$name,'percorso'=>$path,'mime'=>'application/pdf','descrizione'=>sanitize_text_field($r->get_param('description')),'caricato_da'=>get_current_user_id(),'data_caricamento'=>current_time('mysql')));Studio_Security::audit('caricamento_documento_pwa','paziente',$id,array('file'=>$name));return $this->response(array('saved'=>true));}$rows=$wpdb->get_results($wpdb->prepare('SELECT id,nome_file,descrizione,data_caricamento FROM '.Studio_DB::table('documenti').' WHERE paziente_id=%d ORDER BY id DESC',$id));foreach($rows as $x)$x->download=rest_url('studio/v1/documents/'.absint($x->id).'/download');return $this->response($rows);}
 public function api_patient_invoices($r){global $wpdb;$id=(int)$r['id'];$t=Studio_DB::table('fatture');$rows=$wpdb->get_results($wpdb->prepare("SELECT id,codice_fattura,data_documento,totale_documento,stato,stato_pagamento,metodo_pagamento FROM $t WHERE paziente_id=%d AND stato!='annullata' ORDER BY id DESC",$id));$inv=$paid=0;foreach($rows as $x)if($x->stato==='emessa'){$inv+=(float)$x->totale_documento;if($x->stato_pagamento==='pagata')$paid+=(float)$x->totale_documento;}return $this->response(array('summary'=>array('invoiced'=>$inv,'paid'=>$paid,'outstanding'=>max(0,$inv-$paid)),'documents'=>$rows));}
 private function year_where($year){return '((anno='.(int)$year.') OR (anno IS NULL AND YEAR(data_documento)='.(int)$year.'))';}
 public function api_accounting($r){global $wpdb;$t=Studio_DB::table('fatture');$p=Studio_DB::table('pazienti');$year=(int)($r->get_param('year')?:current_time('Y'));$w=$this->year_where($year);$years=$wpdb->get_col("SELECT DISTINCT COALESCE(anno,YEAR(data_documento)) y FROM $t ORDER BY y DESC");if(!in_array($year,array_map('intval',$years),true))array_unshift($years,$year);return $this->response(array('year'=>$year,'available_years'=>array_values(array_unique(array_map('intval',$years))),'summary'=>array('issued_count'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE stato='emessa' AND $w"),'draft_count'=>(int)$wpdb->get_var("SELECT COUNT(*) FROM $t WHERE stato='bozza' AND $w"),'collected'=>(float)$wpdb->get_var("SELECT COALESCE(SUM(totale_documento),0) FROM $t WHERE stato='emessa' AND stato_pagamento='pagata' AND $w"),'outstanding'=>(float)$wpdb->get_var("SELECT COALESCE(SUM(totale_documento),0) FROM $t WHERE stato='emessa' AND stato_pagamento='da_pagare' AND $w")),'latest'=>$wpdb->get_results("SELECT f.id,f.codice_fattura,f.data_documento,f.totale_documento,f.stato,f.stato_pagamento,f.metodo_pagamento,p.nome,p.cognome FROM $t f LEFT JOIN $p p ON p.id=f.paziente_id WHERE $w ORDER BY f.id DESC LIMIT 6")));}
 public function api_invoice_list($r){global $wpdb;$t=Studio_DB::table('fatture');$p=Studio_DB::table('pazienti');$year=(int)($r->get_param('year')?:current_time('Y'));$w=$this->year_where($year);return $this->response($wpdb->get_results("SELECT f.id,f.codice_fattura,f.data_documento,f.totale_documento,f.stato,f.stato_pagamento,f.metodo_pagamento,p.nome,p.cognome FROM $t f LEFT JOIN $p p ON p.id=f.paziente_id WHERE $w ORDER BY f.id DESC LIMIT 200"));}
 public function api_invoice($r){global $wpdb;$id=(int)$r['id'];$f=Studio_DB::table('fatture');$p=Studio_DB::table('pazienti');$i=$wpdb->get_row($wpdb->prepare("SELECT f.*,p.nome,p.cognome FROM $f f LEFT JOIN $p p ON p.id=f.paziente_id WHERE f.id=%d",$id));if(!$i)return new WP_Error('not_found','Documento non trovato',array('status'=>404));$i->rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.Studio_DB::table('fatture_righe').' WHERE fattura_id=%d ORDER BY ordine,id',$id));return $this->response($i);}
}
