<?php
if(!defined('ABSPATH'))exit;
class Studio_Security{
 private static $instance;public static function get_instance(){return self::$instance?:(self::$instance=new self());}
 private function __construct(){add_action('wp_login',array($this,'login'),10,2);add_action('admin_menu',array($this,'menu'));add_action('admin_init',array($this,'page_access'));}
 public static function audit($azione,$oggetto='',$id=0,$dettagli=array()){global $wpdb;$ip=isset($_SERVER['REMOTE_ADDR'])?sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'])):'';$wpdb->insert(Studio_DB::table('audit'),array('user_id'=>get_current_user_id(),'azione'=>sanitize_key($azione),'oggetto'=>sanitize_key($oggetto),'oggetto_id'=>intval($id),'dettagli'=>wp_json_encode($dettagli),'ip_hash'=>hash_hmac('sha256',$ip,wp_salt('auth')),'data_evento'=>current_time('mysql')));}
 public function login($name,$user){global $wpdb;$ip=isset($_SERVER['REMOTE_ADDR'])?sanitize_text_field(wp_unslash($_SERVER['REMOTE_ADDR'])):'';$wpdb->insert(Studio_DB::table('audit'),array('user_id'=>$user->ID,'azione'=>'login','oggetto'=>'user','oggetto_id'=>$user->ID,'dettagli'=>wp_json_encode(array('login'=>$name)),'ip_hash'=>hash_hmac('sha256',$ip,wp_salt('auth')),'data_evento'=>current_time('mysql')));}
 public function page_access(){if(isset($_GET['page'])&&strpos(sanitize_key($_GET['page']),'studio-')===0&&sanitize_key($_GET['page'])!=='studio-sicurezza'&&current_user_can(Studio_Roles::CAP_VIEW_SECURITY))self::audit('accesso_pagina','page',0,array('pagina'=>sanitize_key($_GET['page'])));}
 public function menu(){add_submenu_page('studio-professionale','Sicurezza e Audit','Sicurezza',Studio_Roles::CAP_VIEW_SECURITY,'studio-sicurezza',array($this,'render'));}
 public function render(){global $wpdb;$table=Studio_DB::table('audit');$page=max(1,intval($_GET['paged']??1));$per=50;$text=sanitize_text_field($_GET['audit_text']??'');$user_id=intval($_GET['audit_user']??0);$action=sanitize_key($_GET['audit_action']??'');$days=max(0,intval($_GET['audit_days']??0));$from=sanitize_text_field($_GET['audit_from']??'');$to=sanitize_text_field($_GET['audit_to']??'');$where=array('1=1');$args=array();if($text!==''){$like='%'.$wpdb->esc_like($text).'%';$where[]='(a.azione LIKE %s OR a.oggetto LIKE %s OR CAST(a.oggetto_id AS CHAR) LIKE %s OR a.dettagli LIKE %s OR a.ip_hash LIKE %s OR u.display_name LIKE %s OR u.user_email LIKE %s)';for($i=0;$i<7;$i++)$args[]=$like;}if($user_id){$where[]='a.user_id=%d';$args[]=$user_id;}if($action!==''){$where[]='a.azione=%s';$args[]=$action;}if($days>0){$where[]='a.data_evento >= %s';$args[]=date('Y-m-d H:i:s',current_time('timestamp')-$days*DAY_IN_SECONDS);}if($from!==''){$where[]='a.data_evento >= %s';$args[]=$from.' 00:00:00';}if($to!==''){$where[]='a.data_evento <= %s';$args[]=$to.' 23:59:59';}$where_sql=implode(' AND ',$where);$base=" FROM $table a LEFT JOIN {$wpdb->users} u ON u.ID=a.user_id WHERE $where_sql";$count_sql='SELECT COUNT(*)'.$base;$data_sql='SELECT a.*,u.display_name,u.user_email'.$base.' ORDER BY a.id DESC LIMIT %d OFFSET %d';$total=(int)$wpdb->get_var($args?$wpdb->prepare($count_sql,$args):$count_sql);$data_args=array_merge($args,array($per,($page-1)*$per));$logs=$wpdb->get_results($wpdb->prepare($data_sql,$data_args));$users=$wpdb->get_results("SELECT DISTINCT u.ID,u.display_name FROM $table a INNER JOIN {$wpdb->users} u ON u.ID=a.user_id ORDER BY u.display_name");$actions=$wpdb->get_col("SELECT DISTINCT azione FROM $table ORDER BY azione");include STUDIO_PROF_PATH.'templates/security-log.php';}
}
