<?php
if(!defined('ABSPATH'))exit;
final class Studio_PWA_243{
 private static $doc=null;
 public static function init(){add_action('rest_api_init',array(__CLASS__,'routes'),20);add_filter('rest_pre_serve_request',array(__CLASS__,'serve'),10,4);}
 public static function routes(){foreach(array(
  array('/invoice-config','GET','config','invoice_perm'),array('/invoices','POST','create','invoice_perm'),array('/invoices/(?P<id>\d+)','PUT','update','invoice_perm'),array('/invoices/(?P<id>\d+)/send','POST','send','send_perm'),array('/documents/(?P<id>\d+)/download','GET','document','document_perm')
 )as$x)register_rest_route('studio/v1',$x[0],array('methods'=>$x[1],'callback'=>array(__CLASS__,$x[2]),'permission_callback'=>array(__CLASS__,$x[3])));}
 public static function invoice_perm(){return is_user_logged_in()&&current_user_can(Studio_Roles::CAP_MANAGE_INVOICES);}
 public static function send_perm(){return is_user_logged_in()&&current_user_can(Studio_Roles::CAP_SEND_EMAILS);}
 public static function document_perm(){return is_user_logged_in()&&(current_user_can(Studio_Roles::CAP_MANAGE_DOCUMENTS)||current_user_can(Studio_Roles::CAP_VIEW_CLINICAL));}
 private static function ok($d){$r=rest_ensure_response($d);$r->header('Cache-Control','no-store');return$r;}
 public static function config(){global$wpdb;$s=Studio_DB::get_studio_data();return self::ok(array('patients'=>$wpdb->get_results('SELECT id,nome,cognome,email FROM '.Studio_DB::table('pazienti').' ORDER BY cognome,nome'),'services'=>Studio_DB::get_prestazioni(),'fiscal'=>array('cassa'=>(float)$s['cassa_perc'],'ritenuta'=>(float)$s['ritenuta_perc'],'bollo'=>(float)$s['marca_bollo'])));}
 private static function payload($r){$j=$r->get_json_params();$rows=array();$imp=0;foreach(($j['rows']??array())as$n=>$x){$d=sanitize_text_field($x['description']??'');if(!$d)continue;$q=max(.01,(float)($x['quantity']??1));$p=max(0,(float)($x['price']??0));$s=(float)($x['discount']??0);$t=round($q*$p*(1-$s/100),2);$imp+=$t;$rows[]=array('descrizione'=>$d,'quantita'=>$q,'prezzo_unitario'=>$p,'sconto_maggiorazione_perc'=>$s,'totale_riga'=>$t,'ordine'=>$n);}if(!$rows)return new WP_Error('rows','Inserire almeno una prestazione.',array('status'=>422));$st=Studio_DB::get_studio_data();$c=(float)($j['cassa']??$st['cassa_perc']);$i=(float)($j['iva']??0);$rt=(float)($j['ritenuta']??$st['ritenuta_perc']);$tc=round($imp*$c/100,2);$ti=round(($imp+$tc)*$i/100,2);$tr=round($imp*$rt/100,2);$ab=!empty($j['bollo']);$b=$ab?(float)$st['marca_bollo']:0;return array('h'=>array('paziente_id'=>absint($j['patient_id']??0),'stato'=>'bozza','tipo_documento'=>($j['type']??'sanitaria')==='non_sanitaria'?'non_sanitaria':'sanitaria','data_documento'=>sanitize_text_field($j['date']??current_time('Y-m-d')),'valuta'=>'EUR','totale_imponibile'=>$imp,'percentuale_cassa'=>$c,'totale_cassa'=>$tc,'percentuale_iva'=>$i,'totale_iva'=>$ti,'percentuale_ritenuta'=>$rt,'totale_ritenuta'=>$tr,'applica_marca_bollo'=>$ab?1:0,'marca_bollo'=>$b,'totale_documento'=>max(0,round($imp+$tc+$ti+$b-$tr,2)),'stato_pagamento'=>!empty($j['payment_date'])?'pagata':'da_pagare','metodo_pagamento'=>sanitize_text_field($j['payment_method']??''),'data_pagamento'=>!empty($j['payment_date'])?sanitize_text_field($j['payment_date']):null,'note_documento'=>sanitize_textarea_field($j['notes']??'')),'rows'=>$rows,'issue'=>!empty($j['issue']));}
 private static function save($id,$d){global$wpdb;$tf=Studio_DB::table('fatture');$tr=Studio_DB::table('fatture_righe');$new=!$id;if($id){$o=$wpdb->get_row($wpdb->prepare("SELECT stato FROM $tf WHERE id=%d",$id));if(!$o)return new WP_Error('not_found','Fattura non trovata.',array('status'=>404));if($o->stato!=='bozza')return new WP_Error('locked','È possibile modificare solo una bozza.',array('status'=>409));$wpdb->update($tf,$d['h'],array('id'=>$id));$wpdb->delete($tr,array('fattura_id'=>$id));}else{$d['h']['data_creazione']=current_time('mysql');$wpdb->insert($tf,$d['h']);$id=(int)$wpdb->insert_id;}foreach($d['rows']as$row){$row['fattura_id']=$id;$wpdb->insert($tr,$row);}Studio_Invoices::sync_stamp_duty($id);if($d['issue'])Studio_Invoices::issue_invoice($id);Studio_Security::audit($d['issue']?'emissione_fattura_pwa':($new?'creazione_fattura_pwa':'modifica_fattura_pwa'),'fattura',$id);return self::ok(array('saved'=>true,'id'=>$id,'issued'=>$d['issue']));}
 public static function create($r){$d=self::payload($r);return is_wp_error($d)?$d:self::save(0,$d);}public static function update($r){$d=self::payload($r);return is_wp_error($d)?$d:self::save(absint($r['id']),$d);}
 public static function send($r){global$wpdb;$id=absint($r['id']);$st=$wpdb->get_var($wpdb->prepare('SELECT stato FROM '.Studio_DB::table('fatture').' WHERE id=%d',$id));if($st!=='emessa')return new WP_Error('draft','Emetti la fattura prima dell’invio.',array('status'=>409));$x=Studio_PDF::send_invoice_email($id);if(is_wp_error($x))return$x;Studio_Security::audit('invio_fattura_pwa','fattura',$id);return self::ok(array('sent'=>true));}
 public static function document($r){global$wpdb;$d=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Studio_DB::table('documenti').' WHERE id=%d',absint($r['id'])));if(!$d||!is_file($d->percorso))return new WP_Error('not_found','Documento non trovato.',array('status'=>404));$p=realpath($d->percorso);$u=wp_upload_dir();$root=realpath(trailingslashit($u['basedir']).'studio-professionale-docs');if(!$p||!$root||strpos($p,$root.DIRECTORY_SEPARATOR)!==0)return new WP_Error('path','Percorso non valido.',array('status'=>403));self::$doc=array($p,sanitize_file_name($d->nome_file),filesize($p));$x=new WP_REST_Response(null,200);$x->header('Content-Type','application/pdf');$x->header('Content-Disposition','attachment; filename="'.self::$doc[1].'"');return$x;}
 public static function serve($served,$result,$r,$server){if($served||!self::$doc||!preg_match('#/documents/\d+/download$#',$r->get_route()))return$served;$d=self::$doc;self::$doc=null;while(ob_get_level())ob_end_clean();header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$d[1].'"');header('Content-Length: '.$d[2]);header('Cache-Control: no-store');readfile($d[0]);return true;}
}
Studio_PWA_243::init();
