<?php
if (!defined('ABSPATH')) exit;
require_once STUDIO_PROF_PATH.'includes/class-studio-pdf-engine.php';
class Studio_PDF {
 public static function get_storage_dir(){$u=wp_upload_dir();$d=$u['basedir'].'/studio-professionale-docs';wp_mkdir_p($d);return $d;}
 private static function invoice_data($id){global $wpdb;$f=Studio_DB::table('fatture');$p=Studio_DB::table('pazienti');$r=Studio_DB::table('fatture_righe');$i=$wpdb->get_row($wpdb->prepare("SELECT f.*,p.nome,p.cognome,p.codice_fiscale,p.email,p.telefono,p.indirizzo_residenza,p.citta_residenza,p.cap_residenza,p.provincia_residenza FROM $f f LEFT JOIN $p p ON f.paziente_id=p.id WHERE f.id=%d",$id));$rows=$i?$wpdb->get_results($wpdb->prepare("SELECT * FROM $r WHERE fattura_id=%d ORDER BY ordine,id",$id)):array();return array($i,$rows);}
 public static function generate_invoice_pdf($id){global $wpdb;list($i,$rows)=self::invoice_data($id);if(!$i)return false;$s=Studio_DB::get_studio_data();$pdf=new Studio_PDF_Engine();
  $pdf->color('#ffffff');$pdf->rect(0,0,595,86,true);$pdf->color('#334155');$pdf->line(38,82,557,82);$pdf->text(38,35,$s['professionista'],21,true,'#0f172a');$pdf->text(38,56,$s['titolo'],10,false,'#475569');
  $kind=($i->tipo_documento??'sanitaria')==='non_sanitaria'?'FATTURA':'FATTURA SANITARIA';if(($i->tipo_documento??'')==='preventivo')$kind='PREVENTIVO';if(($i->tipo_documento??'')==='nota_credito')$kind='NOTA DI CREDITO';$pdf->text(370,35,$kind,16,true,'#0f172a');$pdf->text(370,57,($i->codice_fattura?:'BOZZA #'.$i->id).'  |  '.date('d/m/Y',strtotime($i->data_documento)),10,false,'#475569');
  $pdf->color('#f8fafc');$pdf->rect(38,108,245,112,true);$pdf->color('#e2e8f0');$pdf->rect(310,108,247,112,true);$pdf->text(52,129,'DATI PROFESSIONISTA',9,true,'#64748b');$y=148;$pdf->text(52,$y,$s['denominazione'],12,true);$pdf->text(52,$y+18,$s['indirizzo']);$pdf->text(52,$y+34,trim($s['cap'].' '.$s['citta'].' ('.$s['provincia'].')'));$pdf->text(52,$y+50,'C.F. '.$s['codice_fiscale'].'   P.IVA '.$s['partita_iva'],9);
  $pdf->text(324,129,'INTESTATARIO',9,true,'#64748b');$pdf->text(324,150,$i->cognome.' '.$i->nome,12,true);$pdf->text(324,169,'C.F. '.$i->codice_fiscale,9);$pdf->wrapped(324,187,trim($i->indirizzo_residenza.' - '.$i->cap_residenza.' '.$i->citta_residenza.' ('.$i->provincia_residenza.')'),215,9,12);
  $top=246;$pdf->color('#ffffff');$pdf->rect(38,$top,519,28,true);$pdf->color('#64748b');$pdf->line(38,$top,557,$top);$pdf->line(38,$top+28,557,$top+28);$pdf->text(48,$top+19,'DESCRIZIONE',9,true,'#0f172a');$pdf->text(355,$top+19,'Q.TA',9,true,'#0f172a');$pdf->text(405,$top+19,'PREZZO',9,true,'#0f172a');$pdf->text(492,$top+19,'IMPORTO',9,true,'#0f172a');$y=$top+28;$alt=false;foreach($rows as $r){$pdf->color($alt?'#f8fafc':'#ffffff');$pdf->rect(38,$y,519,30,true);$pdf->text(48,$y+19,$r->descrizione,9);$pdf->text(362,$y+19,number_format($r->quantita,1,',','.'));$pdf->text(405,$y+19,number_format($r->prezzo_unitario,2,',','.').' EUR');$pdf->text(492,$y+19,number_format($r->totale_riga,2,',','.').' EUR',9,true);$pdf->color('#e2e8f0');$pdf->line(38,$y+30,557,$y+30);$y+=30;$alt=!$alt;if($y>540)break;}
  $y+=18;$pdf->color('#f8fafc');$pdf->rect(330,$y,227,150,true);$ty=$y+24;$pairs=array('Imponibile'=>[$i->totale_imponibile,false]);if($i->totale_cassa>0)$pairs['Cassa previdenziale']=[$i->totale_cassa,false];if($i->totale_iva>0)$pairs['IVA']=[$i->totale_iva,false];if($i->marca_bollo>0)$pairs['Marca da bollo']=[$i->marca_bollo,false];if($i->totale_ritenuta>0)$pairs['Ritenuta']=[$i->totale_ritenuta,true];foreach($pairs as $k=>$v){$pdf->text(344,$ty,$k,9);$pdf->text(480,$ty,($v[1]?'- ':'').number_format($v[0],2,',','.').' EUR',9,true);$ty+=20;}$pdf->color('#0f172a');$pdf->line(344,$ty,543,$ty);$pdf->text(344,$ty+25,'TOTALE',12,true);$pdf->text(465,$ty+25,number_format($i->totale_documento,2,',','.').' EUR',12,true,'#2563eb');
  $pdf->color($i->stato_pagamento==='pagata'?'#dcfce7':'#fee2e2');$pdf->rect(38,$y,260,48,true);$pdf->text(52,$y+20,'STATO PAGAMENTO',8,true,'#64748b');$pdf->text(52,$y+36,$i->stato_pagamento==='pagata'?'SALDATO':'DA PAGARE',11,true,$i->stato_pagamento==='pagata'?'#166534':'#991b1b');if($i->stato_pagamento==='pagata')$pdf->text(145,$y+36,'Metodo: '.($i->metodo_pagamento?:'-'),9,false,'#334155');
  $fy=760;$pdf->color('#e2e8f0');$pdf->line(38,$fy,557,$fy);$pdf->wrapped(38,$fy+18,$s['note_legali'].(!empty($i->note_documento)?' | Note: '.$i->note_documento:''),519,8,10,false,'#64748b');
  $num=$i->numero_fattura?:('BOZZA-'.$i->id);$anno=$i->anno?:date('Y',strtotime($i->data_documento));$name=sanitize_file_name($num.'_'.$anno.'_'.$i->cognome.'_'.$i->nome.'.pdf');$path=self::get_storage_dir().'/'.$name;file_put_contents($path,$pdf->output());$u=wp_upload_dir();$wpdb->update(Studio_DB::table('fatture'),array('pdf_path'=>$path,'pdf_url'=>$u['baseurl'].'/studio-professionale-docs/'.$name),array('id'=>$id));return $path; }
 public static function output_invoice_pdf($id){$f=self::generate_invoice_pdf($id);if(!$f)wp_die('Documento non trovato');header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="'.basename($f).'"');readfile($f);exit;}
 public static function output_privacy_pdf($pid){global $wpdb;$p=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Studio_DB::table('pazienti').' WHERE id=%d',$pid));if(!$p)wp_die('Paziente non trovato');$s=Studio_DB::get_studio_data();$pdf=new Studio_PDF_Engine();$pdf->color('#0f172a');$pdf->rect(0,0,595,82,true);$pdf->text(38,32,'CONSENSO PRIVACY',19,true,'#ffffff');$pdf->text(38,55,$s['denominazione'].' | '.$s['professionista'],10,false,'#cbd5e1');$pdf->color('#f8fafc');$pdf->rect(38,106,519,112,true);$pdf->text(52,128,'DATI IDENTIFICATIVI DEL PAZIENTE',9,true,'#64748b');$pdf->text(52,151,$p->cognome.' '.$p->nome,13,true);$pdf->text(52,172,'Codice fiscale: '.$p->codice_fiscale,9);$pdf->text(52,191,'Nato/a il: '.($p->data_nascita?date('d/m/Y',strtotime($p->data_nascita)):'-').' a '.$p->luogo_nascita.' ('.$p->provincia_nascita.')',9);$pdf->text(52,208,'Residenza: '.trim($p->indirizzo_residenza.' - '.$p->cap_residenza.' '.$p->citta_residenza),9);$pdf->text(38,250,'INFORMATIVA E CONSENSO',12,true,'#0f172a');$y=$pdf->wrapped(38,275,$s['testo_privacy'],519,9,13,false,'#334155');$y=min($y+25,700);$pdf->color('#e2e8f0');$pdf->line(38,$y,250,$y);$pdf->line(345,$y,557,$y);$pdf->text(38,$y+18,'Luogo e data',9,false,'#64748b');$pdf->text(345,$y+18,'Firma del paziente / tutore',9,false,'#64748b');$pdf->text(38,790,$s['professionista'].' - '.$s['titolo'],8,false,'#64748b');header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="Consenso_'.sanitize_file_name($p->cognome.'_'.$p->nome).'.pdf"');echo $pdf->output();exit;}
 public static function send_invoice_email($id){global $wpdb;list($i,$r)=self::invoice_data($id);if(!$i||!is_email($i->email))return new WP_Error('no_recipient','Email paziente non valida');$s=Studio_DB::get_studio_data();$file=self::generate_invoice_pdf($id);$subject='Fattura N. '.$i->codice_fattura.' '.$i->nome.' '.$i->cognome;$payment=$i->stato_pagamento==='pagata'?'SALDATO il '.date_i18n('d/m/Y',strtotime($i->data_pagamento)).' tramite '.($i->metodo_pagamento?:'-'):'DA PAGARE';$body="Gentile {$i->nome} {$i->cognome},\n\nin allegato trova la fattura N. {$i->codice_fattura}.\nData fattura: ".date_i18n('d/m/Y',strtotime($i->data_documento))."\nImporto totale: ".number_format($i->totale_documento,2,',','.')." EUR\nStato pagamento: {$payment}\n\nCordiali saluti,\n{$s['professionista']}";$ok=wp_mail($i->email,$subject,$body,array('From: '.$s['professionista'].' <'.$s['email'].'>'),array($file));if($ok){$wpdb->insert(Studio_DB::table('log'),array('paziente_id'=>$i->paziente_id,'fattura_id'=>$id,'user_id'=>get_current_user_id(),'tipo'=>'invio_fattura_email','dettagli'=>wp_json_encode(array('oggetto'=>$subject,'destinatario'=>$i->email,'fattura'=>$i->codice_fattura,'importo'=>$i->totale_documento,'pagamento'=>$payment,'file'=>basename($file))),'data_evento'=>current_time('mysql')));Studio_Security::audit('invio_fattura_email','fattura',$id,array('destinatario'=>$i->email));}return $ok?true:new WP_Error('mail_failed','Invio fallito. Verifica FluentSMTP.');}
}
