<?php
if(!defined('ABSPATH'))exit;
require_once STUDIO_PROF_PATH.'includes/class-studio-simple-pdf.php';
class Studio_PDF {
 public static function get_storage_dir(){$u=wp_upload_dir();$d=$u['basedir'].'/studio-professionale-docs';wp_mkdir_p($d);return $d;}
 private static function data($id){global $wpdb;$f=Studio_DB::table('fatture');$p=Studio_DB::table('pazienti');$r=Studio_DB::table('fatture_righe');$i=$wpdb->get_row($wpdb->prepare("SELECT f.*,p.nome,p.cognome,p.codice_fiscale,p.email,p.indirizzo_residenza,p.cap_residenza,p.citta_residenza,p.provincia_residenza FROM $f f LEFT JOIN $p p ON p.id=f.paziente_id WHERE f.id=%d",$id));return array($i,$i?$wpdb->get_results($wpdb->prepare("SELECT * FROM $r WHERE fattura_id=%d ORDER BY ordine,id",$id)):array());}
 public static function generate_invoice_pdf($id){global $wpdb;list($i,$rows)=self::data($id);if(!$i)return false;$s=Studio_DB::get_studio_data();$type=($i->tipo_documento??'sanitaria')==='non_sanitaria'?'FATTURA':'FATTURA SANITARIA';if(($i->tipo_documento??'')==='preventivo')$type='PREVENTIVO';if(($i->tipo_documento??'')==='nota_credito')$type='NOTA DI CREDITO';$num=$i->numero_fattura?:('BOZZA-'.$i->id);$anno=$i->anno?:date('Y',strtotime($i->data_documento));$name=sanitize_file_name($num.'_'.$anno.'_'.$i->cognome.'_'.$i->nome.'.pdf');$lines=array($s['professionista'],$s['titolo'],$type.' '.$i->codice_fattura,'Data: '.date('d/m/Y',strtotime($i->data_documento)),'Paziente: '.$i->cognome.' '.$i->nome,'Codice fiscale: '.$i->codice_fiscale,'');foreach($rows as $r)$lines[]=$r->descrizione.' - '.number_format($r->totale_riga,2,',','.').' EUR';$lines[]= '';$lines[]='Totale documento: '.number_format($i->totale_documento,2,',','.').' EUR';$lines[]='Stato pagamento: '.($i->stato_pagamento==='pagata'?'SALDATO':'DA PAGARE');$path=self::get_storage_dir().'/'.$name;file_put_contents($path,Studio_Simple_PDF::create($lines));$u=wp_upload_dir();$wpdb->update(Studio_DB::table('fatture'),array('pdf_path'=>$path,'pdf_url'=>$u['baseurl'].'/studio-professionale-docs/'.$name),array('id'=>$id));return $path;}
 public static function output_invoice_pdf($id){$f=self::generate_invoice_pdf($id);if(!$f)wp_die('Documento non trovato');header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="'.basename($f).'"');readfile($f);exit;}
 public static function output_privacy_pdf($pid){global $wpdb;$p=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Studio_DB::table('pazienti').' WHERE id=%d',$pid));if(!$p)wp_die('Paziente non trovato');$s=Studio_DB::get_studio_data();$lines=array('CONSENSO PRIVACY',$s['professionista'],$p->cognome.' '.$p->nome,'CF: '.$p->codice_fiscale,'',strip_tags($s['testo_privacy']),'','Data e firma: __________________________');$pdf=Studio_Simple_PDF::create($lines);header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="Consenso_'.$p->cognome.'_'.$p->nome.'.pdf"');echo $pdf;exit;}
 public static function send_invoice_email($id){global $wpdb;list($i,$rows)=self::data($id);if(!$i||!is_email($i->email))return new WP_Error('no_recipient','Email paziente non valida');$s=Studio_DB::get_studio_data();$file=self::generate_invoice_pdf($id);$ok=wp_mail($i->email,'Documento '.$i->codice_fattura,'In allegato il documento fiscale.','From: '.$s['professionista'].' <'.$s['email'].'>',array($file));if($ok)$wpdb->insert(Studio_DB::table('log'),array('paziente_id'=>$i->paziente_id,'fattura_id'=>$id,'user_id'=>get_current_user_id(),'tipo'=>'invio_fattura','dettagli'=>wp_json_encode(array('email'=>$i->email,'file'=>basename($file),'numero'=>$i->codice_fattura)),'data_evento'=>current_time('mysql')));return $ok?true:new WP_Error('mail_failed','Invio non riuscito. Verifica FluentSMTP.');}
}
