<?php
if(!defined('ABSPATH'))exit;
class Studio_Clinical_Profile{
 private static $instance; public static function get_instance(){return self::$instance?:(self::$instance=new self());}
 private function __construct(){add_action('admin_init',array($this,'save_profile'));add_action('admin_init',array($this,'save_vocabulary'));}
 public static function defaults(){return array(
  array('id'=>'intelligenze','name'=>'Intelligenze','icon'=>'dashicons-lightbulb','color'=>'#6366f1','items'=>array('Artistica','Comunicativa','Emotiva','Esperienziale','Gestionale','Linguistica','Logico matematica','Motoria','Musicale','Pragmatica','Procedurale','Sensoriale','Spirituale')),
  array('id'=>'neuro_personalita','name'=>'Neuro personalità','icon'=>'dashicons-networking','color'=>'#a855f7','items'=>array('Cortisolica','Dopaminica','Endorfinica','Noradrenalinica','Ossitocina','Serotoninica','Testosteronica')),
  array('id'=>'ferite_maschere','name'=>'5 ferite e maschere','icon'=>'dashicons-universal-access','color'=>'#f59e0b','items'=>array('Abbandono - dipendente','Ingiustizia - rigido','Rifiuto - fuggitivo','Tradimento - controllore','Umiliazione - masochista')),
  array('id'=>'stile_attaccamento','name'=>'Stile di attaccamento','icon'=>'dashicons-admin-links','color'=>'#3b82f6','items'=>array('Ansioso - ambivalente','Disorganizzato - caotico','Insicuro - evitante','Sicuro - equilibrato')),
  array('id'=>'maschere_primarie','name'=>'Maschere primarie','icon'=>'dashicons-shield','color'=>'#10b981','items'=>array('Adolescente','Adulto','Bambino','Saggio')),
  array('id'=>'dipendenze','name'=>'Dipendenze','icon'=>'dashicons-warning','color'=>'#f43f5e','items'=>array('Alcol','Cannabinoidi','Cibo','Cocaina','Lavoro','Ludopatia','Palestra','Pasticche','Sesso','Shopping')),
  array('id'=>'doc','name'=>'DOC','icon'=>'dashicons-list-view','color'=>'#06b6d4','items'=>array('Pensieri o immagini ossessive','Rituali di controllo e pulizia')),
  array('id'=>'sogni','name'=>'Sogni','icon'=>'dashicons-cloud','color'=>'#8b5cf6','items'=>array('Frammentati e incostanti','Lucidi e articolati con molti dettagli')),
  array('id'=>'psicosomatica','name'=>'Psicosomatica','icon'=>'dashicons-heart','color'=>'#14b8a6','items'=>array('Acufeni','Allergie','Alopecia','Ansia','Asma','Attacchi di panico','Cisti','Colite','Depressione','Emicranie','Emorroidi','Epidemici','Epilessia','Gastrite','Herpes','Ictus','Infarti','Interventi chirurgici','Intolleranze','Linfomi','M. autoimmuni','Morbo Crohn','Neurodegenerative','Occhi','Ortopedici','Parodontite','Prolasso','Psoriasi','Psicosi','Renali','Tic neurologici','Trombosi','Tumori','Urinari')),
  array('id'=>'abusi','name'=>'Abusi','icon'=>'dashicons-lock','color'=>'#ef4444','items'=>array('Corporei','Psicologici','Sessuali'))
 );}
 public static function vocabulary(){return Studio_DB::get_setting('studio_clinical_vocabulary',self::defaults());}
 public static function get($pid){global $wpdb;$r=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Studio_DB::table('profili_clinici').' WHERE paziente_id=%d',$pid));return $r?json_decode($r->profilo_json,true):array();}
 public function render($pid){if(!current_user_can(Studio_Roles::CAP_VIEW_CLINICAL))wp_die('Accesso negato');global $wpdb;$patient=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Studio_DB::table('pazienti').' WHERE id=%d',$pid));if(!$patient)wp_die('Paziente non trovato');$categories=self::vocabulary();$selected=self::get($pid);include STUDIO_PROF_PATH.'templates/clinical-profile.php';}
 public function save_profile(){if(!isset($_POST['studio_save_clinical_profile']))return;check_admin_referer('studio_save_clinical_profile');if(!current_user_can(Studio_Roles::CAP_VIEW_CLINICAL))wp_die('Accesso negato');$pid=intval($_POST['patient_id']);$allowed=array();foreach(self::vocabulary() as $c)$allowed[$c['id']]=array_flip($c['items']);$raw=$_POST['clinical']??array();$clean=array();foreach($raw as $cid=>$items){$cid=sanitize_key($cid);if(!isset($allowed[$cid])||!is_array($items))continue;foreach($items as $item){$item=sanitize_text_field(wp_unslash($item));if(isset($allowed[$cid][$item]))$clean[$cid][]=$item;}}global $wpdb;$table=Studio_DB::table('profili_clinici');$old=self::get($pid);$wpdb->replace($table,array('paziente_id'=>$pid,'profilo_json'=>wp_json_encode($clean,JSON_UNESCAPED_UNICODE),'utente_modifica'=>get_current_user_id(),'data_aggiornamento'=>current_time('mysql'),'data_creazione'=>current_time('mysql')),array('%d','%s','%d','%s','%s'));Studio_Security::audit($old?'modifica_profilo_clinico':'creazione_profilo_clinico','paziente',$pid,array('prima'=>$old,'dopo'=>$clean));wp_safe_redirect(admin_url('admin.php?page=studio-pazienti&action=view&id='.$pid.'&profile_saved=1'));exit;}
 public function save_vocabulary(){if(!isset($_POST['studio_save_clinical_vocabulary']))return;check_admin_referer('studio_save_clinical_vocabulary');if(!current_user_can(Studio_Roles::CAP_MANAGE_STUDIO))wp_die('Accesso negato');$names=$_POST['clinical_category_name']??array();$items=$_POST['clinical_category_items']??array();$colors=$_POST['clinical_category_color']??array();$out=array();foreach($names as $i=>$name){$name=sanitize_text_field(wp_unslash($name));if(!$name)continue;$lines=preg_split('/\R/',wp_unslash($items[$i]??''));$vals=array_values(array_unique(array_filter(array_map('sanitize_text_field',$lines))));$out[]=array('id'=>sanitize_key($name).'_'.$i,'name'=>$name,'icon'=>'dashicons-tag','color'=>sanitize_hex_color($colors[$i]??'#2563eb')?:'#2563eb','items'=>$vals);}Studio_DB::update_setting('studio_clinical_vocabulary',$out);Studio_Security::audit('modifica_vocabolario_clinico','impostazioni',0);wp_safe_redirect(admin_url('admin.php?page=studio-impostazioni&clinical_updated=1'));exit;}
}
